In [1]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())
print(torch.cuda.device_count())



2.5.1+cu124
True
1


In [16]:
import numpy as np
# 1. Reshaping, viewing, stacking, squeezing, and unsqueezing tensors
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
print("Original Tensor:")
print(x)

# Reshaping
reshaped_x = x.reshape(3, 2)
print("\nReshaped Tensor (3, 2):")
print(reshaped_x)

# Viewing
viewed_x = x.view(3, 2)
print("\nViewed Tensor (3, 2):")
print(viewed_x)

# Stacking
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
stacked_tensor = torch.stack((a, b), dim=0)
print("\nStacked Tensor (along dim=0):")
print(stacked_tensor)

# Squeezing
x_with_ones = torch.tensor([[[1, 2, 3]]])  # shape (1, 1, 3)
squeezed_x = x_with_ones.squeeze()
print("\nSqueezed Tensor:")
print(squeezed_x)

# Unsqueezing
unsqueezed_x = x.unsqueeze(1)  # shape (1, 2, 3)
print("\nUnsqueezed Tensor (added dimension at position 1):")
print(unsqueezed_x)

Original Tensor:
tensor([[1, 2, 3],
        [4, 5, 6]])

Reshaped Tensor (3, 2):
tensor([[1, 2],
        [3, 4],
        [5, 6]])

Viewed Tensor (3, 2):
tensor([[1, 2],
        [3, 4],
        [5, 6]])

Stacked Tensor (along dim=0):
tensor([[1, 2, 3],
        [4, 5, 6]])

Squeezed Tensor:
tensor([1, 2, 3])

Unsqueezed Tensor (added dimension at position 1):
tensor([[[1, 2, 3]],

        [[4, 5, 6]]])


In [4]:
# 2. Using torch.permute()
# Permuting a tensor changes the order of its dimensions
perm_x = x.permute(1, 0)  # Swap the rows and columns
print("\nPermuted Tensor:")
print(perm_x)


Permuted Tensor:
tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [17]:
# 3. Indexing in tensors
# Accessing a specific element
print("\nElement at (1,2):")
print(x[1, 2])

# Slicing the tensor
sliced_x = x[:, 1:]  # All rows, starting from the second column
print("\nSliced Tensor (all rows, starting from second column):")
print(sliced_x)




Element at (1,2):
tensor(6)

Sliced Tensor (all rows, starting from second column):
tensor([[2, 3],
        [5, 6]])


In [7]:
# 4. Converting numpy arrays to tensors and vice versa
np_array = np.array([[1, 2, 3], [4, 5, 6]])
tensor_from_np = torch.tensor(np_array)
print("\nNumpy array converted to tensor:")
print(tensor_from_np)

tensor_back_to_np = tensor_from_np.numpy()
print("\nTensor converted back to numpy array:")
print(tensor_back_to_np)


Numpy array converted to tensor:
tensor([[1, 2, 3],
        [4, 5, 6]])

Tensor converted back to numpy array:
[[1 2 3]
 [4 5 6]]


In [18]:
# 5. Create a random tensor with shape (7, 7)
random_tensor = torch.randn(7, 7)
print("\nRandom Tensor (7x7):")
print(random_tensor)

# 6. Perform matrix multiplication
# Matrix multiplication requires appropriate shapes. Let's transpose the second tensor.
second_tensor = torch.randn(1, 7)
print("\nSecond Random Tensor (1x7):")
print(second_tensor)

result = torch.matmul(random_tensor, second_tensor.t())  # Transpose the second tensor
print("\nResult of Matrix Multiplication (7x1):")
print(result)



Random Tensor (7x7):
tensor([[ 0.1984,  0.7821,  1.0391, -0.7245, -0.8489, -1.2169, -0.0810],
        [ 1.3615, -2.0615,  0.6741, -1.3233, -1.3598, -0.8667, -0.5640],
        [-2.0565, -0.3567,  0.9571, -0.6619, -0.8285, -0.6057, -0.1354],
        [ 0.7471,  0.6118,  1.8678, -0.2616, -0.2501,  0.5011,  0.2600],
        [-1.6370,  0.1577,  0.3957, -1.3677, -2.9662, -1.7178, -0.5824],
        [-0.6153,  1.5496,  0.5989, -0.6377, -2.2858, -0.3677, -0.3866],
        [-1.0370,  0.5920, -0.7557,  0.3917,  0.7470,  1.3798,  1.2877]])

Second Random Tensor (1x7):
tensor([[ 0.6569,  0.0413, -1.3750,  0.1321,  0.1583, -0.7080,  0.3778]])

Result of Matrix Multiplication (7x1):
tensor([[-0.6652],
        [-0.1072],
        [-2.5226],
        [-2.3828],
        [-1.2671],
        [-1.4955],
        [ 0.0619]])


In [13]:
# 7. Send two random tensors of shape (2, 3) to the GPU (if available)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
tensor1 = torch.randn(2, 3).to(device)
tensor2 = torch.randn(2, 3).to(device)
print("\nTensor 1 on GPU:")
print(tensor1)

print("\nTensor 2 on GPU:")
print(tensor2)



Tensor 1 on GPU:
tensor([[-0.8340,  1.3860, -0.5730],
        [ 3.1271, -0.1201, -0.6222]], device='cuda:0')

Tensor 2 on GPU:
tensor([[0.5833, 1.3165, 1.0786],
        [1.0186, 0.8852, 2.0187]], device='cuda:0')


In [ ]:

# 8. Perform matrix multiplication on tensors from 6

tensor_a = torch.randn(2, 3).to(device)
tensor_b = torch.randn(3, 2).to(device)
matrix_mul_result = torch.mm(tensor_a, tensor_b)
print("\nResult of Matrix Multiplication (2x2) on GPU:")
print(matrix_mul_result)


In [19]:

# 9. Find the maximum and minimum values of the output from 7
max_val = tensor1.max()
min_val = tensor1.min()
print("\nMaximum Value of the Output:")
print(max_val)

print("\nMinimum Value of the Output:")
print(min_val)
max_val = tensor2.max()
min_val = tensor2.min()
print("\nMaximum Value of the Output:")
print(max_val)

print("\nMinimum Value of the Output:")
print(min_val)
# 10. Find the maximum and minimum index values of the output from 7
max_idx = tensor1.argmax()
min_idx = tensor1.argmin()
print("\nIndex of Maximum Value in the Output:")
print(max_idx)

print("\nIndex of Minimum Value in the Output:")
print(min_idx)



Maximum Value of the Output:
tensor(3.1271, device='cuda:0')

Minimum Value of the Output:
tensor(-0.8340, device='cuda:0')

Maximum Value of the Output:
tensor(2.0187, device='cuda:0')

Minimum Value of the Output:
tensor(0.5833, device='cuda:0')

Index of Maximum Value in the Output:
tensor(3, device='cuda:0')

Index of Minimum Value in the Output:
tensor(0, device='cuda:0')


In [15]:

# 11. Create a random tensor and remove 1-dimension using squeeze()
torch.manual_seed(7)
tensor_1 = torch.randn(1, 1, 1, 10)
print("\nTensor with shape (1, 1, 1, 10):")
print(tensor_1)
print("\nShape of Tensor:")
print(tensor_1.shape)

tensor_2 = tensor_1.squeeze()
print("\nTensor after removing dimensions of size 1:")
print(tensor_2)
print("\nShape of Squeezed Tensor:")
print(tensor_2.shape)



Tensor with shape (1, 1, 1, 10):
tensor([[[[-0.1468,  0.7861,  0.9468, -1.1143,  1.6908, -0.8948, -0.3556,
            1.2324,  0.1382, -1.6822]]]])

Shape of Tensor:
torch.Size([1, 1, 1, 10])

Tensor after removing dimensions of size 1:
tensor([-0.1468,  0.7861,  0.9468, -1.1143,  1.6908, -0.8948, -0.3556,  1.2324,
         0.1382, -1.6822])

Shape of Squeezed Tensor:
torch.Size([10])
