In [1]:
import torch
print("PyTorch version:", torch.__version__)
print("CUDA Available:", torch.cuda.is_available())
print("CUDA Version:", torch.version.cuda)
print("GPU Name:", torch.cuda.get_device_name(0) if torch.cuda.is_available() else "No GPU")


PyTorch version: 2.4.1+cu121
CUDA Available: True
CUDA Version: 12.1
GPU Name: Quadro P620


In [2]:
import numpy as np
# 1. Reshaping, viewing, stacking, squeezing, and unsqueezing tensors
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
print("Original Tensor:")
print(x)

# Reshaping
reshaped_x = x.reshape(3, 2)
print("\nReshaped Tensor (3, 2):")
print(reshaped_x)

# Viewing
viewed_x = x.view(3, 2)
print("\nViewed Tensor (3, 2):")
print(viewed_x)

# Stacking
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
stacked_tensor = torch.stack((a, b), dim=0)
print("\nStacked Tensor (along dim=0):")
print(stacked_tensor)

# Squeezing
x_with_ones = torch.tensor([[[1, 2, 3]]])  # shape (1, 1, 3)
squeezed_x = x_with_ones.squeeze()
print("\nSqueezed Tensor:")
print(squeezed_x)

# Unsqueezing
unsqueezed_x = x.unsqueeze(1)  # shape (1, 2, 3)
print("\nUnsqueezed Tensor (added dimension at position 1):")
print(unsqueezed_x)

Original Tensor:
tensor([[1, 2, 3],
        [4, 5, 6]])

Reshaped Tensor (3, 2):
tensor([[1, 2],
        [3, 4],
        [5, 6]])

Viewed Tensor (3, 2):
tensor([[1, 2],
        [3, 4],
        [5, 6]])

Stacked Tensor (along dim=0):
tensor([[1, 2, 3],
        [4, 5, 6]])

Squeezed Tensor:
tensor([1, 2, 3])

Unsqueezed Tensor (added dimension at position 1):
tensor([[[1, 2, 3]],

        [[4, 5, 6]]])


In [3]:
# 2. Using torch.permute()
# Permuting a tensor changes the order of its dimensions
perm_x = x.permute(1, 0)  # Swap the rows and columns
print("\nPermuted Tensor:")
print(perm_x)


Permuted Tensor:
tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [4]:
# 3. Indexing in tensors
# Accessing a specific element
print("\nElement at (1,2):")
print(x[1, 2])

# Slicing the tensor
sliced_x = x[:, 1:]  # All rows, starting from the second column
print("\nSliced Tensor (all rows, starting from second column):")
print(sliced_x)


Element at (1,2):
tensor(6)

Sliced Tensor (all rows, starting from second column):
tensor([[2, 3],
        [5, 6]])


In [5]:
# 4. Converting numpy arrays to tensors and vice versa
np_array = np.array([[1, 2, 3], [4, 5, 6]])
tensor_from_np = torch.tensor(np_array)
print("\nNumpy array converted to tensor:")
print(tensor_from_np)

tensor_back_to_np = tensor_from_np.numpy()
print("\nTensor converted back to numpy array:")
print(tensor_back_to_np)


Numpy array converted to tensor:
tensor([[1, 2, 3],
        [4, 5, 6]])

Tensor converted back to numpy array:
[[1 2 3]
 [4 5 6]]


In [8]:
# 5. Create a random tensor with shape (7, 7)
random_tensor = torch.randn(7, 7)
print("\nRandom Tensor (7x7):")
print(random_tensor)

# 6. Perform matrix multiplication
# Matrix multiplication requires appropriate shapes. Let's transpose the second tensor.
second_tensor = torch.randn(1, 7)
print("\nSecond Random Tensor (1x7):")
print(second_tensor)

result = torch.matmul(random_tensor, second_tensor.t())  # Transpose the second tensor
print("\nResult of Matrix Multiplication (7x1):")
print(result)


Random Tensor (7x7):
tensor([[ 1.5804, -0.1361,  0.1544,  0.2750, -0.1897, -0.1168, -1.5155],
        [ 0.1911, -1.0023, -0.2451, -0.0372,  0.7787,  0.2958, -1.8349],
        [-0.8442,  0.0635, -2.3183,  0.8133,  0.3009, -1.9914,  0.7120],
        [ 2.0411,  0.1017, -0.2368, -0.2849,  1.9446, -2.1282,  0.4910],
        [-2.4963, -0.3523, -1.5606,  0.7658, -1.4392, -0.3615, -1.0875],
        [-0.3725,  0.5063, -2.4089,  0.3564,  0.7772,  0.5113,  1.2297],
        [-0.1738, -1.1299,  0.3147, -1.1702, -1.3149,  0.7810,  0.6312]])

Second Random Tensor (1x7):
tensor([[-0.4881, -0.2899, -0.6331,  0.8228,  0.7665, -1.4387,  0.3072]])

Result of Matrix Multiplication (7x1):
tensor([[-1.0462],
        [-0.0704],
        [ 5.8449],
        [ 3.5930],
        [ 2.0215],
        [ 2.0912],
        [-2.6873]])


In [7]:
# 7. Send two random tensors of shape (2, 3) to the GPU (if available)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
tensor1 = torch.randn(2, 3).to(device)
tensor2 = torch.randn(2, 3).to(device)
print("\nTensor 1 on GPU:")
print(tensor1)

print("\nTensor 2 on GPU:")
print(tensor2)


Tensor 1 on GPU:
tensor([[-1.0093, -0.1264,  0.4504],
        [-1.2588, -0.1148, -0.2644]], device='cuda:0')

Tensor 2 on GPU:
tensor([[-0.5243, -1.6670,  0.7001],
        [-0.1973, -0.8577,  0.1584]], device='cuda:0')


In [9]:
max_val = tensor1.max()
min_val = tensor1.min()
print("\nMaximum Value of the Output:")
print(max_val)

print("\nMinimum Value of the Output:")
print(min_val)
max_val = tensor2.max()
min_val = tensor2.min()
print("\nMaximum Value of the Output:")
print(max_val)

print("\nMinimum Value of the Output:")
print(min_val)
# 10. Find the maximum and minimum index values of the output from 7
max_idx = tensor1.argmax()
min_idx = tensor1.argmin()
print("\nIndex of Maximum Value in the Output:")
print(max_idx)

print("\nIndex of Minimum Value in the Output:")
print(min_idx)


Maximum Value of the Output:
tensor(0.4504, device='cuda:0')

Minimum Value of the Output:
tensor(-1.2588, device='cuda:0')

Maximum Value of the Output:
tensor(0.7001, device='cuda:0')

Minimum Value of the Output:
tensor(-1.6670, device='cuda:0')

Index of Maximum Value in the Output:
tensor(2, device='cuda:0')

Index of Minimum Value in the Output:
tensor(3, device='cuda:0')


In [11]:
torch.manual_seed(7)
tensor_1 = torch.randn(1, 1, 1, 10)
print("\nTensor with shape (1, 1, 1, 10):")
print(tensor_1)
print("\nShape of Tensor:")
print(tensor_1.shape)

tensor_2 = tensor_1.squeeze()
print("\nTensor after removing dimensions of size 1:")
print(tensor_2)
print("\nShape of Squeezed Tensor:")
print(tensor_2.shape)


Tensor with shape (1, 1, 1, 10):
tensor([[[[-0.1468,  0.7861,  0.9468, -1.1143,  1.6908, -0.8948, -0.3556,
            1.2324,  0.1382, -1.6822]]]])

Shape of Tensor:
torch.Size([1, 1, 1, 10])

Tensor after removing dimensions of size 1:
tensor([-0.1468,  0.7861,  0.9468, -1.1143,  1.6908, -0.8948, -0.3556,  1.2324,
         0.1382, -1.6822])

Shape of Squeezed Tensor:
torch.Size([10])
